/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/Form/BaseButton.vue')['default']
    BaseInput: typeof import('./components/Form/BaseInput.vue')['default']
    ImgInput: typeof import('./components/Form/ImgInput.vue')['default']
    Loader: typeof import('./components/App/Loader.vue')['default']
    Modal: typeof import('./components/App/Modal.vue')['default']
    NewsModal: typeof import('./components/Modals/NewsModal.vue')['default']
    ProjectModal: typeof import('./components/Modals/ProjectModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceModal: typeof import('./components/Modals/ServiceModal.vue')['default']
    TeamsModal: typeof import('./components/Modals/TeamsModal.vue')['default']
  }
}
